# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

config_setting(
    name = "env_silicon_owner_gb_rom_ext",
    define_values = {
        "FW_ENV": "silicon_owner_gb_rom_ext",
    },
    visibility = ["//visibility:public"],
)

config_setting(
    name = "env_fpga_cw310_rom_with_fake_keys",
    define_values = {
        "FW_ENV": "fpga_cw310_rom_with_fake_keys",
    },
    visibility = ["//visibility:public"],
)

config_setting(
    name = "env_fpga_cw310_sival_rom_ext",
    define_values = {
        "FW_ENV": "fpga_cw310_sival_rom_ext",
    },
    visibility = ["//visibility:public"],
)

config_setting(
    name = "env_fpga_cw310_test_rom",
    define_values = {
        "FW_ENV": "fpga_cw310_test_rom",
    },
    visibility = ["//visibility:public"],
)

config_setting(
    name = "env_silicon_owner_a2_rom_ext",
    define_values = {
        "FW_ENV": "silicon_owner_a2_rom_ext",
    },
    visibility = ["//visibility:public"],
)

config_setting(
    name = "env_silicon_owner_sival_rom_ext",
    define_values = {
        "FW_ENV": "silicon_owner_sival_rom_ext",
    },
    visibility = ["//visibility:public"],
)
